on:
  push:
  pull_request:
jobs:
  compile_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Compile sketch
        run: arduino-cli compile --profile controllino_micro
      - name: Lint sketch
        uses: arduino/arduino-lint-action@v2
